
name: Update Weather in README

on:
  schedule:
    - cron: "15 */6 * * *"   # 6 saatte bir, aktiviteden 15 dk sonra
  workflow_dispatch:

jobs:
  update-weather:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: pip install requests
      - name: Update weather section
        env:
          OWM_API_KEY: ${{ secrets.OWM_API_KEY }}
          CITY: Istanbul
          COUNTRY: TR
        run: |
          python scripts/weather.py
      - name: Commit changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add README.md
            git commit -m "chore: update weather & timestamp"
            git push
          fi
